import React from "react";
import DocPage, { A, List, P, Strong } from "../components/DocPage";
import { POLICY_DATES, SITE, mailto } from "../data/site";

const sections = [
  {
    id: "not-advice",
    title: "Not investment advice",
    body: (
      <>
        <P>
          {SITE.name} is a research and screening tool. It is <Strong>not</Strong> investment, financial, tax or legal
          advice, and it does not recommend buying, selling or holding any security.
        </P>
        <P>
          {SITE.operator} is <Strong>not registered with the Securities and Exchange Board of India (SEBI)</Strong> as an
          Investment Adviser or a Research Analyst. Scores, labels such as &ldquo;Strong&rdquo; or &ldquo;Weak&rdquo;,
          rankings, sentiment tags and model outputs are automated statistical signals, not personal recommendations. They
          do not take your finances, goals or risk tolerance into account.
        </P>
      </>
    ),
  },
  {
    id: "how-scores-work",
    title: "What the scores can and can't do",
    body: (
      <>
        <P>
          Rankings combine a market model (price trend relative to the NIFTY Smallcap 250), a financial model (growth,
          profitability, balance-sheet and cash-flow quality from company filings) and news sentiment. See{" "}
          <A to="/about#methodology">how InvestIQ works</A>.
        </P>
        <List
          items={[
            <>They are tested on history (&ldquo;walk-forward&rdquo;, 2019 to 2026). <Strong>Past performance does not guarantee future results</Strong>, and relationships that held in the past can stop working.</>,
            "They rank companies relative to each other. A top-ranked stock can still fall, and in our tests even the best-ranked group beat the index only about half the time per individual stock.",
            "Historical tests include only companies listed today, so they overstate past returns (survivorship bias).",
            "Momentum-led scores can change quickly and may rank recently rallied, volatile or thinly traded stocks highly.",
          ]}
        />
      </>
    ),
  },
  {
    id: "data",
    title: "Data may be wrong or late",
    body: (
      <P>
        Prices, financial statements and news come from third parties (including NSE and Upstox) and are processed
        automatically. They can be delayed, incomplete or parsed incorrectly, and automated sentiment can misread an
        announcement. Check the original exchange filing or your broker before acting on anything.
      </P>
    ),
  },
  {
    id: "risk",
    title: "Investing involves risk",
    body: (
      <P>
        Investments in securities markets are subject to market risk, and you can lose some or all of the money you invest.
        Small and mid-sized companies can be especially volatile and illiquid. Read all related documents carefully before
        investing, and consider speaking to a SEBI-registered Investment Adviser.
      </P>
    ),
  },
  {
    id: "responsibility",
    title: "Your decisions are your own",
    body: (
      <P>
        You alone are responsible for your investment decisions. {SITE.operator} accepts no liability for any loss or
        damage arising from use of, or reliance on, anything on {SITE.name}. See the{" "}
        <A to="/terms#liability">Terms of Use</A>.
      </P>
    ),
  },
  {
    id: "conflicts",
    title: "Conflicts of interest",
    body: (
      <P>
        {SITE.name} does not accept payment from companies to feature or rank them, and rankings are generated by the same
        automated method for every company. The operator may personally hold securities that appear on the site.
        Questions: <A href={mailto("Disclaimer question")}>{SITE.contactEmail}</A>.
      </P>
    ),
  },
];

export default function Disclaimer() {
  return (
    <DocPage
      index="L3"
      label="Legal"
      title="DISCLAIMER"
      tabTitle="Investment Disclaimer"
      intro="InvestIQ helps you research. It doesn't tell you what to buy."
      updated={POLICY_DATES.disclaimer}
      sections={sections}
    />
  );
}
